### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by q86388304** [mjjonone/mjj#12]
在https://panel.vpsfree.es/部署JS时遇到
Running...
chmod: cannot access 'run': No such file or directory
./start.sh: line 59: ./run: No such file or directory
子进程退出，退出码 127
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image

**Comment by mjjonone** [comment]
重新部署或者在仓库下载run 上传

**Comment by Ty2005** [comment]
下载run文件上传， 错误码变了
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
v20.8.0
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; if [[ "${MAIN_FILE}" == "*.js" ]]; then /usr/local/bin/node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; else /usr/local/bin/ts-node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; fi

up to date, audited 1 package in 2s
found 0 vulnerabilities
赋权成功: ./start.sh
输出：Downloading start file...
curl: (6) Could not resolve host: github.com
输出：Download completed.
输出：run file already exists, skipping download.
Running...
./start.sh: line 52: ./run: cannot execute binary file: Exec format error
子进程退出，退出码 126
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
v20.8.0

**Comment by caco12138** [comment]
我的是这样，目前找不到解决方法

输出：Downloading start file...
curl: (6) Could not resolve host: github.com
输出：Download completed.
输出：run file already exists, skipping download.
Running...
./start.sh: line 52: ./run: cannot execute binary file: Exec format error
子进程退出，退出码 126
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
v20.8.0
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; if [[ "${MAIN_FILE}" == "*.js" ]]; then /usr/local/bin/node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; else /usr/local/bin/ts-node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; fi

up to date, audited 1 package in 2s
found 0 vulnerabilities
赋权成功: ./start.sh
输出：Downloading start file...
curl: (6) Could not resolve host: github.com
输出：Download completed.
run file already exists, skipping download.
Running...
./start.sh: line 52: ./run: cannot execute binary file: Exec format error
子进程退出，退出码 126
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by mjjonone** [comment]
下载run-arm那个重命名run上传

**Comment by caco12138** [comment]
两个run都试过了，还是这样

输出：Downloading start file...
curl: (6) Could not resolve host: github.com
输出：Download completed.
输出：run file already exists, skipping download.
Running...
输出：Failed to set permissions: chmod ./start: no such file or directory
子进程退出，退出码 1
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
v20.8.0
:/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; if [[ "${MAIN_FILE}" == "*.js" ]]; then /usr/local/bin/node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; else /usr/local/bin/ts-node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; fi

up to date, audited 1 package in 2s
found 0 vulnerabilities
赋权成功: ./start.sh
输出：Downloading start file...
curl: (6) Could not resolve host: github.com
输出：Download completed.
run file already exists, skipping download.
Running...
输出：Failed to set permissions: chmod ./start: no such file or directory
子进程退出，退出码 1
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by mjjonone** [comment]
> 两个run都试过了，还是这样
> 
> 输出：Downloading start file... curl: (6) Could not resolve host: github.com 输出：Download completed. 输出：run file already exists, skipping download. Running... 输出：Failed to set permissions: chmod ./start: no such file or directory 子进程退出，退出码 1 container@pterodactyl~ Server marked as offline... [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 0 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds... [Pterodactyl Daemon]: Updating process configuration files... [Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds... container@pterodactyl~ Server marked as starting... [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... [Pterodactyl Daemon]: Finished pulling Docker container image v20.8.0 :/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; if [[ "${MAIN_FILE}" == "*.js" ]]; then /usr/local/bin/node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; else /usr/local/bin/ts-node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; fi
> 
> up to date, audited 1 package in 2s found 0 vulnerabilities 赋权成功: ./start.sh 输出：Downloading start file... curl: (6) Could not resolve host: github.com 输出：Download completed. run file already exists, skipping download. Running... 输出：Failed to set permissions: chmod ./start: no such file or directory 子进程退出，退出码 1 container@pterodactyl~ Server marked as offline... [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 0 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

你看log，缺什么上传什么呗

**Comment by mjjonone** [comment]
是平台自身的机器网络出现问题，无解

**Comment by ivangreat** [comment]
> 两个run都试过了，还是这样
> 
> 输出：Downloading start file... curl: (6) Could not resolve host: github.com 输出：Download completed. 输出：run file already exists, skipping download. Running... 输出：Failed to set permissions: chmod ./start: no such file or directory 子进程退出，退出码 1 container@pterodactyl~ Server marked as offline... [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 0 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds... [Pterodactyl Daemon]: Updating process configuration files... [Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds... container@pterodactyl~ Server marked as starting... [Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete... [Pterodactyl Daemon]: Finished pulling Docker container image v20.8.0 :/home/container$ if [[ -d .git ]] && [[ ${AUTO_UPDATE} == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; if [[ "${MAIN_FILE}" == "*.js" ]]; then /usr/local/bin/node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; else /usr/local/bin/ts-node "/home/container/${MAIN_FILE}" ${NODE_ARGS}; fi
> 
> up to date, audited 1 package in 2s found 0 vulnerabilities 赋权成功: ./start.sh 输出：Downloading start file... curl: (6) Could not resolve host: github.com 输出：Download completed. run file already exists, skipping download. Running... 输出：Failed to set permissions: chmod ./start: no such file or directory 子进程退出，退出码 1 container@pterodactyl~ Server marked as offline... [Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ---------- [Pterodactyl Daemon]: Exit code: 0 [Pterodactyl Daemon]: Out of memory: false [Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

确实你是主机的网络问题，设置proxy变量就阔以了。另外伪装域名似乎无效，让我折腾俩小时都连不上，换个域名OK了。。。
