### ISSUE TITLE
Argo 不通

### ISSUE THREAD

**Issue by linzjian666** [mjjonone/mjj#13]
使用 Json 固定域名后 Argo 无法使用，但是临时域名一切正常

**Comment by mjjonone** [comment]
修复成功，可以再次试试

**Comment by linzjian666** [comment]
![屏幕截图_2023-10-29_09-30-28](https://github.com/mjjonone/mjj/assets/63142068/90ac643f-61b1-4296-b949-f47b7d5d3831)
还是用不了，使用JSON会导致cc无法启动
