### ISSUE TITLE
连不上了

### ISSUE THREAD

**Issue by wanbangshucheng** [mjjonone/mjj#17]
![image](https://github.com/mjjonone/mjj/assets/115765860/da6ac208-6c8b-4473-a676-232652b60637)
有节点输出，但事实是-1

**Comment by mjjonone** [comment]
请给出具体log

**Comment by 14790897** [comment]
![图片](https://github.com/mjjonone/mjj/assets/121866954/f630a2ff-ff1c-4241-b0c8-0241065e5b79)

**Comment by wanbangshucheng** [comment]
![Screenshot_20240324_131924](https://github.com/mjjonone/mjj/assets/115765860/9b88443d-86a8-44dc-8180-4df0e87e5e6c)
back4app这个平台的

**Comment by wanbangshucheng** [comment]
没人理我了。。。
