### ISSUE TITLE
新版玩具里面cc不运行，argo不通

### ISSUE THREAD

**Issue by xiaozhiob** [mjjonone/mjj#6]
![image](https://github.com/mjjonone/mjj/assets/52733598/7f0c6ce3-65ee-4193-bc35-ea77ac38ea15)

新版mjj玩具里面cc不运行，argo不通！！！！

旧版的mjj依然在运行，全部正常。

**Comment by hotren1977** [comment]
昨天重构后，每个版本都有问题

**Comment by mjjonone** [comment]
> ![image](https://user-images.githubusercontent.com/52733598/265544025-7f0c6ce3-65ee-4193-bc35-ea77ac38ea15.png)
> 
> 新版mjj玩具里面cc不运行，argo不通！！！！
> 
> 旧版的mjj依然在运行，全部正常。

什么平台了

**Comment by mjjonone** [comment]
> 昨天重构后，每个版本都有问题

能具体说明一下吗

**Comment by hotren1977** [comment]
myridax，用的node.js

**Comment by hotren1977** [comment]
[9a1e537](https://github.com/mjjonone/mjj/commit/9a1e5373b7e6dff016104594234a5449967c2940)
这个版本的测试，用Argo Json的失败，只能用Argo Token或临时隧道

**Comment by mjjonone** [comment]
> [9a1e537](https://github.com/mjjonone/mjj/commit/9a1e5373b7e6dff016104594234a5449967c2940) 这个版本的测试，用Argo Json的失败，只能用Argo Token或临时隧道

我会尽快修复的

**Comment by xiaozhiob** [comment]
> > ![image](https://user-images.githubusercontent.com/52733598/265544025-7f0c6ce3-65ee-4193-bc35-ea77ac38ea15.png)
> > 新版mjj玩具里面cc不运行，argo不通！！！！
> > 旧版的mjj依然在运行，全部正常。
> 
> 什么平台了

lunes

**Comment by lemongad** [comment]
> > > ![image](https://user-images.githubusercontent.com/52733598/265544025-7f0c6ce3-65ee-4193-bc35-ea77ac38ea15.png)
> > > 新版mjj玩具里面cc不运行，argo不通！！！！
> > > 旧版的mjj依然在运行，全部正常。
> > 
> > 
> > 什么平台了
> 
> lunes

现在不能用json，等我下午修复

**Comment by mjjonone** [comment]
> > > > ![image](https://user-images.githubusercontent.com/52733598/265544025-7f0c6ce3-65ee-4193-bc35-ea77ac38ea15.png)
> > > > 新版mjj玩具里面cc不运行，argo不通！！！！
> > > > 旧版的mjj依然在运行，全部正常。
> > > 
> > > 
> > > 什么平台了
> > 
> > 
> > lunes
> 
> 现在不能用json，等我下午修复

已经修复

**Comment by mjjonone** [comment]
> [9a1e537](https://github.com/mjjonone/mjj/commit/9a1e5373b7e6dff016104594234a5449967c2940) 这个版本的测试，用Argo Json的失败，只能用Argo Token或临时隧道

已经修复

**Comment by ye-cao** [comment]
最新版本还是不能用json
