### ISSUE TITLE
huggingface平台只要添加Argo相关变量，运行就突然中止报错。测试只能使用临时隧道，但2天左右app就会休眠，还要手动登录网站重启获取新的节点。有没有办法解决？

### ISSUE THREAD

**Issue by parunback** [mjjonone/mjj#7]
感觉hug是不是设立了Argo域名的检测机制？为啥我自己发布docker，直接在源代码内填写Argo变量搭建，正运行代码着突然就会报错，无法搭建。以直接在hug平台添加ARGO变量的方式也会搭建失败，只要不添加自己的Argo变量，默认使用临时隧道就能搭建成功。但临时隧道有个问题，搭建后的节点2天后就失效，无法使用订阅获取新的，必须手动登录网站，网站提示容器停止，请重启spaces。重启一下才会获取新的节点，订阅才会正常，隧道名才会改变。想知道有没有办法能够让节点搭建持久一点？

ps：我知道我的问题又臭又长，作者大大可以看心情回复~

**Comment by mjjonone** [comment]
可能存在检测，用临时隧道解决，你搜索uptimerobot，然后监测项目的网址，可以实现保活

**Comment by parunback** [comment]
用了好像还是不行，保活不了哇。大佬你试了吗？能否保活成功？
